from __future__ import annotations

import random
import uuid
from decimal import Decimal

from django.utils import timezone

from apps.demo_data.config import DemoDataConfig
from apps.payments.models import Payment


class PaymentGenerator:
    def __init__(self, config: DemoDataConfig, rng: random.Random):
        self.config = config
        self.rng = rng

    def settle_order(self, order) -> None:
        """
        Apply realistic payment/fulfillment outcomes using Order.mark_as_paid
        and a mock payments.Payment row (no Rapyd).
        """
        roll = self.rng.random()
        if roll < self.config.paid_ratio:
            tx_id = f"demo_tx_{uuid.uuid4().hex[:16]}"
            order.mark_as_paid(transaction_id=tx_id)
            self._create_mock_payment(order, paid=True, tx_id=tx_id)

            # Advance fulfillment for a subset of paid orders
            if self.rng.random() < self.config.delivered_ratio:
                order.status = "delivered"
                order.save(update_fields=["status", "updated_at"])
            elif self.rng.random() < 0.5:
                order.status = "shipped"
                order.save(update_fields=["status", "updated_at"])
        elif roll < self.config.paid_ratio + self.config.payment_failed_ratio:
            order.mark_as_payment_failed()
            self._create_mock_payment(order, paid=False, tx_id=None)
        # else: leave as pending_payment

    def _create_mock_payment(self, order, *, paid: bool, tx_id: str | None) -> Payment:
        now = timezone.now()
        rapyd_id = f"demo_pay_{uuid.uuid4().hex[:20]}"
        return Payment.objects.create(
            user=order.buyer,
            order=order,
            rapyd_payment_id=rapyd_id,
            merchant_reference_id=str(order.id),
            customer_token=f"demo_cus_{order.buyer_id}",
            amount=Decimal(str(order.total)),
            original_amount=Decimal(str(order.total)),
            currency_code="COP",
            country_code="CO",
            status="CLO" if paid else "ERR",
            paid=paid,
            refunded=False,
            payment_method_type="demo_card",
            description="Demo payment generated by generate_demo_data",
            failure_code="" if paid else "DEMO_DECLINED",
            failure_message="" if paid else "Simulated payment failure",
            rapyd_created_at=now,
            rapyd_paid_at=now if paid else None,
            webhook_metadata={"source": "demo_data", "transaction_id": tx_id},
        )
