FROM python:3.11-slim

WORKDIR /app

COPY Backend/requirements.txt /app/
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt gunicorn whitenoise

COPY Backend/ /app/
COPY ml/ /app/ml/

EXPOSE 8000

CMD ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn main_app.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60"]