# Generated by Django 5.2.14 on 2026-07-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerprofile",
            name="allergies",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
