# Generated by Django 5.2.14 on 2026-06-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JWTBlacklist",
        ),
    ]
