# Generated by Django 5.2.14 on 2026-07-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rapyd_payment_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID único del pago de Rapyd",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "merchant_reference_id",
                    models.CharField(
                        db_index=True,
                        help_text="Referencia del pedido/orden",
                        max_length=255,
                    ),
                ),
                (
                    "customer_token",
                    models.CharField(
                        db_index=True,
                        help_text="Token del cliente en Rapyd",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Monto del pago", max_digits=15
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Monto original", max_digits=15
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        default="COP",
                        help_text="Código de moneda (ej: COP, USD)",
                        max_length=3,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        default="CO", help_text="Código del país", max_length=2
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CLO", "Cerrado/Completado"),
                            ("PEN", "Pendiente"),
                            ("ERR", "Error"),
                            ("REV", "Revertido"),
                            ("INIT", "Iniciado"),
                            ("CAN", "Cancelado"),
                            ("REF", "Reembolsado"),
                            ("EXP", "Expirado"),
                            ("SUCCESS", "Exitoso"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        help_text="Estado actual del pago",
                        max_length=20,
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                ("refunded", models.BooleanField(default=False)),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monto reembolsado",
                        max_digits=15,
                    ),
                ),
                (
                    "payment_method_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de método de pago (ej: co_visa_m_card)",
                        max_length=100,
                    ),
                ),
                (
                    "payment_method_data",
                    models.JSONField(
                        blank=True,
                        help_text="Información completa del método de pago",
                        null=True,
                    ),
                ),
                (
                    "auth_code",
                    models.CharField(
                        blank=True, help_text="Código de autorización", max_length=100
                    ),
                ),
                (
                    "authentication_result",
                    models.JSONField(
                        blank=True,
                        help_text="Resultado de autenticación 3DS",
                        null=True,
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        blank=True, help_text="URL de redirección de Rapyd"
                    ),
                ),
                (
                    "complete_payment_url",
                    models.URLField(blank=True, help_text="URL de éxito"),
                ),
                (
                    "error_payment_url",
                    models.URLField(blank=True, help_text="URL de error"),
                ),
                ("is_partial", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("failure_code", models.CharField(blank=True, max_length=100)),
                ("failure_message", models.TextField(blank=True)),
                ("ewallet_id", models.CharField(blank=True, max_length=255)),
                ("ewallets", models.JSONField(blank=True, null=True)),
                (
                    "webhook_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Metadata adicional del webhook",
                        null=True,
                    ),
                ),
                (
                    "rapyd_created_at",
                    models.DateTimeField(
                        help_text="Fecha de creación en Rapyd (convertida de timestamp)"
                    ),
                ),
                (
                    "rapyd_paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de pago en Rapyd (convertida de timestamp)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rapyd_payment_id"],
                        name="payments_pa_rapyd_p_f43289_idx",
                    ),
                    models.Index(
                        fields=["merchant_reference_id"],
                        name="payments_pa_merchan_0af1ee_idx",
                    ),
                    models.Index(
                        fields=["customer_token"], name="payments_pa_custome_226031_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="payments_pa_status_21ed42_idx",
                    ),
                ],
            },
        ),
    ]
