# Generated by Django 5.2.14 on 2026-07-25 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_activate_order_models"),
        ("payments", "0002_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Orden asociada si corresponde (UUID)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="authentication.order",
            ),
        ),
    ]
